---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zenith-client.fullname" . }}
  labels: {{ include "zenith-client.labels" . | nindent 4 }}
stringData: {{ include "zenith-client.config" . | nindent 2 }}
